In [4]:
import mdptoolbox
import numpy as np

### Defining the problem (MDP)

*State*: Roll step, terminal

*Action*: Roll, Quit

*Reward*: +[side of the die], -[bankroll]

*Transition*: 
Probabilities of isBadSide (stochastic)
Quitting is probability is 1 (deterministic)

Output = State-value at state 0

### Transition Probabilities

In [110]:
# Example N = 6
# Max states = N * 3 + 2
T = np.zeros((2, 20, 20))

# Action: Roll (Stochastic)
#        0  1  2  3   4    5    6   7  8  9  10 11 12 13 14 15 16 17 18 19
T[0] = [[0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/2], # 0
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 1 
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 2
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 3
#        0  1  2  3  4  5  6  7  8    9    10   11 12 13 14 15 16 17 18 19
        [0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 0, 0, 0, 0, 0, 1/2], # 4
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 0, 0, 0, 0, 1/2], # 5
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 0, 0, 0, 1/2], # 6
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 0, 0, 1/2], # 7
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 0, 1/2], # 8
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 0, 1/2], # 9
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 0, 1/2], # 10
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 0, 1/2], # 11
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/6, 1/2], # 12
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/6, 1/2 + 1/6], # 13
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1/6, 1/2 + 2/6], # 14
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 15
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 16
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 17
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 18
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]] # 19

# Action: Quit (Deterministic)
#        0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19
T[1] = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 0
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 1 
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 2
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 3
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 4
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 5
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 6
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 7
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 8
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 9
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 10
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 11
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 12
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 13
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 14
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 15
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 16
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 17
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], # 18
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]] # 19

In [115]:
# Reward
R = np.zeros((2, 20, 20))

# Action: Roll
#        0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19
R[0] = [[0, 0, 0, 0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 0
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 1 
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 2
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 3
        [0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, -4], # 4
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, -5], # 5
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, 0, 0, 0, 0, -6], # 6
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, 0, 0, 0, -7], # 7
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, 0, 0, -8], # 8
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, 0, -9], # 9
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, 0, -10], # 10
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, 0, -11], # 11
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 6, -12], # 12
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, -13], # 13
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -14], # 14
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -15], # 15
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -16], # 16
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -17], # 17
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -18], # 18
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]] # 19
# Action: Quit
#        0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16 17 18 19
R[1] = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 0
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 1 
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 2
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 3
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 4
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 5
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 6
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 7
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 8
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 9
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 10
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 11
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 12
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 13
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 14
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 15
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 16
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 17
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # 18
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]] # 19

In [116]:
vi = mdptoolbox.mdp.ValueIteration(T, R, 1.0)
vi.run()

In [117]:
optimal_policy = vi.policy
expected_values = vi.V

In [118]:
print(optimal_policy)
print(expected_values)

(0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(2.5833333333333335, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


In [259]:
def expected_values(isBadSide):
    # get the good indicies
    good_indicies = []
    for i, isBad in enumerate(isBadSide):
        if not isBad:
            good_indicies.append(i + 1)
    print(good_indicies)
    
    N = len(isBadSide)
    max_states_n = 3 * N + 2

    T = np.zeros((2, max_states_n, max_states_n))
    
    T_roll = np.zeros((max_states_n, max_states_n))
    T_quit = np.zeros((max_states_n, max_states_n))
    
    R = np.zeros((2, max_states_n, max_states_n))
    
    R_roll = np.zeros((max_states_n, max_states_n))
    R_quit = np.zeros((max_states_n, max_states_n))
    
    possible_rows = [0] + good_indicies
    print(possible_rows)
    
    # build T and R matricies
    for row in range(0, max_states_n):
        # row vector
        T_roll_row = np.zeros(max_states_n)
        R_roll_row = np.zeros(max_states_n)
        
        if row in possible_rows:
            terminal_p = 1
            for idx in good_indicies:
                col = idx + row
                if col < max_states_n - 1:
                    T_roll_row[col] = 1 / N
                    terminal_p = terminal_p - (1 / N)
                    
                    R_roll_row[col] = idx
                    
                    if col not in possible_rows:
                        possible_rows.append(col)
            T_roll_row[max_states_n - 1] = terminal_p
            R_roll_row[max_states_n - 1] = -row
        else:
            T_roll_row[max_states_n - 1] = 1.0
        
        T_roll[row] = T_roll_row
        R_roll[row] = R_roll_row
        
        T_quit_row = np.zeros(max_states_n)
        T_quit_row[max_states_n - 1] = 1.0
        T_quit[row] = T_quit_row
        
    print(R_roll)
    T[0] = T_roll
    T[1] = T_quit
    R[0] = R_roll
    R[1] = R_quit
    
    vi = mdptoolbox.mdp.ValueIteration(T, R, 1.0)
    vi.run()
    
    optimal_policy = vi.policy
    expected_values = vi.V
    
    print(optimal_policy)
    print(expected_values)

In [260]:
expected_values([1, 1, 1, 0, 0, 0])

[4, 5, 6]
[0, 4, 5, 6]
[[  0.   0.   0.   0.   4.   5.   6.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   4.   5.   6.   0.   0.   0.
    0.   0.   0.   0.   0.  -4.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   4.   5.   6.   0.   0.
    0.   0.   0.   0.   0.  -5.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   4.   5.   6.   0.
    0.   0.   0.   0.   0.  -6.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   4.   5.
    6.   0.   0.   0.   0.  -8.]
 [  0.   0.   0.   0.   0.   0. 

In [261]:
expected_values([1,1,1,1,0,0,0,0,1,0,1,0,1,1,0,1,0,0,0,1,0])

[5, 6, 7, 8, 10, 12, 15, 17, 18, 19, 21]
[0, 5, 6, 7, 8, 10, 12, 15, 17, 18, 19, 21]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0. -62.]
 [  0.   0.   0. ...   0.   0. -63.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(7.379980563654034, 0.0, 0.0, 0.0, 0.0, 4.399092970521546, 3.836734693877555, 3.2970521541950157, 2.780045351473927, 0.0, 1.8095238095238146, 1.3333333333333393, 0.857142857142863, 0.3809523809523876, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


In [262]:
expected_values([1,1,1,1,1,1,0,1,0,1,1,0,1,0,1,0,0,1,0,0,1,0])

[7, 9, 12, 14, 16, 17, 19, 20, 22]
[0, 7, 9, 12, 14, 16, 17, 19, 20, 22]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0. -65.]
 [  0.   0.   0. ...   0.   0. -66.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(6.314049586776859, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.045454545454543, 0.0, 0.8636363636363598, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


In [263]:
# Problem 1
# N=9,
# isBadSide={0,0,1,0,1,0,1,1,0,}
expected_values([0,0,1,0,1,0,1,1,0])

[1, 2, 4, 6, 9]
[0, 1, 2, 4, 6, 9]
[[  0.   1.   2.   0.   4.   0.   6.   0.   0.   9.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   1.   2.   0.   4.   0.   6.   0.   0.   9.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -1.]
 [  0.   0.   0.   1.   2.   0.   4.   0.   6.   0.   0.   9.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -2.]
 [  0.   0.   0.   0.   1.   2.   0.   4.   0.   6.   0.   0.   9.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -3.]
 [  0.   0.   0.   0.   0.   1.   2.   0.   4.   0.   6.   0.   0.   9.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -4.]
 [  0.   0.   0.   0.   0.   0.   1.   2.   0.   4.   0.   6.   0.   0.
    9.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -5.]
 [  0.   0.   0.   0.   0.   0.   0.   1.   2.   0.  

In [264]:
# Problem 2
# N=9,
# isBadSide={0,0,0,0,1,1,0,1,0,}
expected_values([0,0,0,0,1,1,0,1,0])

[1, 2, 3, 4, 7, 9]
[0, 1, 2, 3, 4, 7, 9]
[[  0.   1.   2.   3.   4.   0.   0.   7.   0.   9.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   1.   2.   3.   4.   0.   0.   7.   0.   9.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -1.]
 [  0.   0.   0.   1.   2.   3.   4.   0.   0.   7.   0.   9.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -2.]
 [  0.   0.   0.   0.   1.   2.   3.   4.   0.   0.   7.   0.   9.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -3.]
 [  0.   0.   0.   0.   0.   1.   2.   3.   4.   0.   0.   7.   0.   9.
    0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -4.]
 [  0.   0.   0.   0.   0.   0.   1.   2.   3.   4.   0.   0.   7.   0.
    9.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   -5.]
 [  0.   0.   0.   0.   0.   0.   0.   1.   2. 

In [265]:
# Problem 3
# N=27,
# isBadSide={0,1,1,0,0,1,0,1,0,0,1,1,1,1,0,1,0,0,0,1,1,1,0,0,0,0,0,}
expected_values([0,1,1,0,0,1,0,1,0,0,1,1,1,1,0,1,0,0,0,1,1,1,0,0,0,0,0])

[1, 4, 5, 7, 9, 10, 15, 17, 18, 19, 23, 24, 25, 26, 27]
[0, 1, 4, 5, 7, 9, 10, 15, 17, 18, 19, 23, 24, 25, 26, 27]
[[  0.   1.   0. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.  -1.]
 [  0.   0.   0. ...   0.   0.  -2.]
 ...
 [  0.   0.   0. ...   0.   1. -80.]
 [  0.   0.   0. ...   0.   0. -81.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(10.123122409253886, 9.501697655438143, 8.899315606408205, 8.315099679717761, 7.736183250752125, 7.172832746076055, 6.615230135647259, 6.05937218772133, 5.504965360776252, 4.952954256376452, 4.416735295587314, 3.898435051533881, 3.384631038447726, 2.8849090735621776, 2.3890149960550886, 1.908068956053575, 1.44378773937275, 0.9822689630645604, 0.52126200274347, 0.07407407407406019, 0.0, 0.0, 0.0, 0.0, 0.0

In [266]:
# Problem 4
# N=7,
# isBadSide={0,0,1,1,1,0,1,}
expected_values([0,0,1,1,1,0,1])

[1, 2, 6]
[0, 1, 2, 6]
[[  0.   1.   2.   0.   0.   0.   6.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   1.   2.   0.   0.   0.   6.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  -1.]
 [  0.   0.   0.   1.   2.   0.   0.   0.   6.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  -2.]
 [  0.   0.   0.   0.   1.   2.   0.   0.   0.   6.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  -3.]
 [  0.   0.   0.   0.   0.   1.   2.   0.   0.   0.   6.   0.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  -4.]
 [  0.   0.   0.   0.   0.   0.   1.   2.   0.   0.   0.   6.   0.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  -5.]
 [  0.   0.   0.   0.   0.   0.   0.   1.   2.   0.   0.   0.   6.   0.
    0.   0.   0.   0.   0.   0.   0.   0.  -6.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   1.   2.   0.   0.   0.   6.
    0.   0.   0.   0.   0.   0.   0.   0.  -7.]
 [  0.   0.   0. 

In [267]:
# Problem 5
# N=14,
# isBadSide={0,1,1,0,0,1,0,1,0,0,1,1,1,1,}
expected_values([0,1,1,0,0,1,0,1,0,0,1,1,1,1])

[1, 4, 5, 7, 9, 10]
[0, 1, 4, 5, 7, 9, 10]
[[  0.   1.   0. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.  -1.]
 [  0.   0.   0. ...   0.   0.  -2.]
 ...
 [  0.   0.   0. ...   0.   1. -41.]
 [  0.   0.   0. ...   0.   0. -42.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(2.7419825072886295, 2.106413994169096, 1.491253644314868, 0.8775510204081624, 0.2857142857142847, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


In [268]:
# Problem 6
# N=20,
# isBadSide={0,0,1,1,1,1,1,1,0,0,1,0,1,0,0,0,1,1,1,0,}
expected_values([0,0,1,1,1,1,1,1,0,0,1,0,1,0,0,0,1,1,1,0])

[1, 2, 9, 10, 12, 14, 15, 16, 20]
[0, 1, 2, 9, 10, 12, 14, 15, 16, 20]
[[  0.   1.   2. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.  -1.]
 [  0.   0.   0. ...   0.   0.  -2.]
 ...
 [  0.   0.   0. ...   0.   1. -59.]
 [  0.   0.   0. ...   0.   0. -60.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(5.397975000000001, 4.786925000000002, 4.175875000000001, 3.5648250000000017, 2.953843750000002, 2.343068750000003, 1.733875000000003, 1.1275000000000035, 0.5500000000000036, 4.440892098500626e-15, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


In [269]:
# Problem 7
# N=26,
# isBadSide={0,0,0,1,1,0,1,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,0,}
expected_values([0,0,0,1,1,0,1,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,0,0,0])

[1, 2, 3, 6, 8, 9, 11, 12, 15, 16, 18, 19, 21, 22, 24, 25, 26]
[0, 1, 2, 3, 6, 8, 9, 11, 12, 15, 16, 18, 19, 21, 22, 24, 25, 26]
[[  0.   1.   2. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.  -1.]
 [  0.   0.   0. ...   0.   0.  -2.]
 ...
 [  0.   0.   0. ...   0.   1. -77.]
 [  0.   0.   0. ...   0.   0. -78.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(12.652812529069408, 12.010507359132083, 11.387368662583288, 10.784016271800889, 10.192778532618544, 9.614057153235185, 9.053688585331422, 8.504445907612041, 7.96711310399375, 7.447284058422442, 6.937938326594229, 6.4392858783618685, 5.95637643316733, 5.482532559295379, 5.011659993693548, 4.550939434702091, 4.106160764673919, 3.669631877266109, 3.2427465925210535, 2.830796925696657, 2.42592047160452

In [270]:
# Problem 8
# N=10,
# isBadSide={0,1,0,0,1,0,0,0,1,1,}
expected_values([0,1,0,0,1,0,0,0,1,1])

[1, 3, 4, 6, 7, 8]
[0, 1, 3, 4, 6, 7, 8]
[[  0.   1.   0. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.  -1.]
 [  0.   0.   0. ...   0.   0.  -2.]
 ...
 [  0.   0.   0. ...   0.   1. -29.]
 [  0.   0.   0. ...   0.   0. -30.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(3.5902000000000003, 2.9890999999999996, 2.4362, 1.9014999999999995, 1.4050999999999998, 0.9509999999999994, 0.5099999999999996, 0.09999999999999942, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


In [271]:
# Problem 9
# N=22,
# isBadSide={0,1,0,1,1,1,0,0,1,1,1,0,1,0,1,0,0,0,1,0,0,0,}
expected_values([0,1,0,1,1,1,0,0,1,1,1,0,1,0,1,0,0,0,1,0,0,0])

[1, 3, 7, 8, 12, 14, 16, 17, 18, 20, 21, 22]
[0, 1, 3, 7, 8, 12, 14, 16, 17, 18, 20, 21, 22]
[[  0.   1.   0. ...   0.   0.   0.]
 [  0.   0.   1. ...   0.   0.  -1.]
 [  0.   0.   0. ...   0.   0.  -2.]
 ...
 [  0.   0.   0. ...   0.   1. -65.]
 [  0.   0.   0. ...   0.   0. -66.]
 [  0.   0.   0. ...   0.   0.   0.]]
(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0)
(8.381932586571953, 7.782652312000544, 7.190744313912981, 6.618707738542446, 6.050568608701588, 5.501468478929031, 4.954489959702202, 4.409522061334603, 3.868652243699196, 3.350146847892899, 2.8504456662796205, 2.3516025203196445, 1.853062461580487, 1.3582832456799334, 0.8822314049586708, 0.40909090909090207, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0

In [ ]:
# Prpo